### ISSUE TITLE
BU cash 1.1.1.0 does not find a blocksorce.

### ISSUE THREAD

**Issue by Sounds-Like** [gandrewstone/bitcoin#759] opened 2017-08-20 20:41 UTC
After upgrading the BUcash node to 1.1.1.0 it does not sync with the network anymore.
I have a lot of nodes connected but it does not seam to find any new blocks it will accept?
Windows 10 x64
AMD Phenom 9850
4GB RAM

**Comment by sickpig** [comment] 2017-08-21 14:38
Try this: 
- stop bitcoin-qt 
- delete `peers.dat` from your data directory 
- add this 2 params to your `bitcoin.conf`: ` forcednsseed=1` and `usednsseed=seed.bitcoinunlimited.info`
- restart `bitcoin-qt`

**Comment by Sounds-Like** [comment] 2017-08-27 22:34
This does not seam to work for me. in the log I get this.
2017-08-25 13:56:00 ERROR: AcceptBlockHeader: block 0000000000000000004fd350a59be2f51449859652d891f41c78ab9a663b4944 height 478662 is marked invalid
2017-08-25 13:56:00 ERROR: invalid header received
2017-08-25 13:56:00 ProcessMessages(headers, 162003 bytes) FAILED peer=7
2017-08-25 13:56:08 ERROR: AcceptBlockHeader: block 0000000000000000004fd350a59be2f51449859652d891f41c78ab9a663b4944 height 478662 is marked invalid
2017-08-25 13:56:08 ERROR: invalid header received
2017-08-25 13:56:08 ProcessMessages(headers, 162003 bytes) FAILED peer=9
2017-08-25 13:58:01 Initial headers were either not received or not received before the timeout - disconnecting peer=176.9.46.231:8333 (7)
2017-08-25 13:58:01 ERROR: AcceptBlockHeader: block 0000000000000000004fd350a59be2f51449859652d891f41c78ab9a663b4944 height 478662 is marked invalid
2017-08-25 13:58:01 ERROR: invalid header received
2017-08-25 13:58:01 ProcessMessages(headers, 162003 bytes) FAILED peer=12
2017-08-25 13:58:08 Initial headers were either not received or not received before the timeout - disconnecting peer=[2001:0:9d38:6abd:10df:2bbc:a14b:94f4]:8333 (9)
2017-08-25 13:58:09 ERROR: AcceptBlockHeader: block 0000000000000000004fd350a59be2f51449859652d891f41c78ab9a663b4944 height 478662 is marked invalid
2017-08-25 13:58:09 ERROR: invalid header received
2017-08-25 13:58:09 ProcessMessages(headers, 162003 bytes) FAILED peer=13
2017-08-25 14:00:02 Initial headers were either not received or not received before the timeout - disconnecting peer=89.10.155.88:8333 (12)
2017-08-25 14:00:02 ERROR: AcceptBlockHeader: block 0000000000000000004fd350a59be2f51449859652d891f41c78ab9a663b4944 height 478662 is marked invalid
2017-08-25 14:00:02 ERROR: invalid header received
2017-08-25 14:00:02 ProcessMessages(headers, 162003 bytes) FAILED peer=14
2017-08-25 14:00:09 Initial headers were either not received or not received before the timeout - disconnecting peer=[2607:f748:1200:f8:21e:67ff:fe99:8f07]:8333 (13)
2017-08-25 14:00:16 ERROR: AcceptBlockHeader: block 0000000000000000004fd350a59be2f51449859652d891f41c78ab9a663b4944 height 478662 is marked invalid
2017-08-25 14:00:16 ERROR: invalid header received
2017-08-25 14:00:16 ProcessMessages(headers, 162003 bytes) FAILED peer=15

**Comment by sickpig** [comment] 2017-09-07 12:42
@Sounds-Like 

I gave you the wrong dns seed address, I should have written: 

`usednsseed=btccash-seeder.bitcoinunlimited.info`

Could please redo what I describe in my first response and while at it you could also upgrade to the lastest version of BUcash (1.1.1.1)

**Comment by sickpig** [comment] 2018-05-03 10:30
@Sounds-Like any success in reproducing the problem with the latest version of BUcash (1.3.0.0)?

**Comment by sickpig** [comment] 2018-05-30 15:57
@Sounds-Like closing for now due to the fact I'm not able to reproduce. Feel free to reopen it if the issue is still valid.

**Closed as completed by sickpig** 2018-05-30 15:57 UTC
