### ISSUE TITLE
bitcoin-tx should work properly with cashaddr containing ":"

### ISSUE THREAD

**Issue by awemany** [gandrewstone/bitcoin#1286] opened 2018-08-25 17:09 UTC
This doesn't work:

`./bitcoin-tx -regtest -create in="a6203029526697378230d48f70d9f05c1983465a10d9934eecceb5c8ded6fefc:0" outaddr=50.0:bchreg:qqkx25nsqzuzcftu7hs7w2f2ne3ayedefu8mpceqwy`

It results in 
`error: TX output missing or too many separators`

But this does work:

`./bitcoin-tx -regtest -create in="a6203029526697378230d48f70d9f05c1983465a10d9934eecceb5c8ded6fefc:0" outaddr=50.0:qqkx25nsqzuzcftu7hs7w2f2ne3ayedefu8mpceqwy`

However, `newaddress` from bitcoind RPC gives the address as `bchreg:qqkx25nsqzuzcftu7hs7w2f2ne3ayedefu8mpceqwy`. This should behave consistently.

**Comment by WestonReed** [comment] 2018-08-26 00:38
Looks like it's being caused by this line in /src/bitcoin-tx.cpp:
`if (vStrInputParts.size() != 2)`

An easy solution could be to check if the input contains exactly three parts with the 2nd part being `bitcoincash`, `bchtest`, or `bchreg`, then strip the prefix and continue to pass it along, but I'm not sure if it's necessary to keep the prefix for some reason other than convenience.

**Comment by sickpig** [comment] 2018-09-14 09:54
Closing, #1310 fixed it

**Closed as completed by sickpig** 2018-09-14 09:54 UTC
