### ISSUE TITLE
my bitcoind node hang up and I have to kill it

### ISSUE THREAD

**Issue by bitkevin** [gandrewstone/bitcoin#63] opened 2016-08-04 18:59 UTC
- bitcoind unlimited `0.12.1`
- ubuntu `14.04 LTS`

Here is the debug logs, it looks like dead lock issue.

```
2016-08-03 23:57:01 Acceptable block: ver:20000000 time:1470268605 size: 998199 Tx:2254 Sig:3831
2016-08-03 23:57:01 UpdateTip: new best=000000000000000004cbef0311e0f5efe337c1e0957a0669eb8f71276c74234b  height=423560  log2_work=85.081141  tx=146830197  date=2016-08-03 23:56:45 progress=1.000000  cache=137.8MiB(69846tx)
2016-08-03 23:58:33 Node 82.130.103.245:37298 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:00:25 Node 46.101.246.115:37646 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:00:26 Node 82.130.103.245:37460 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:01:21 Node 24.114.102.46:52915 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:01:24 Node 106.185.29.220:43678 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:02:22 Node 24.114.102.46:37583 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:12:06 socket send error 'Connection reset by peer (104)' to 190.247.209.49:64902 (12526)
2016-08-04 00:13:25 Node 106.185.29.220:45502 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:20:10 socket send error 'Connection reset by peer (104)' to 41.182.204.196:61147 (12400)
2016-08-04 00:20:12 Acceptable block: ver:20000000 time:1470269975 size: 998232 Tx:2565 Sig:3998
2016-08-04 00:20:13 UpdateTip: new best=00000000000000000464b83b2fbde49a9cfd910f9520986fecf876ed71c5b934  height=423561  log2_work=85.081171  tx=146832762  date=2016-08-04 00:19:35 progress=1.000000  cache=141.4MiB(74129tx)
2016-08-04 00:20:45 Acceptable block: ver:20000000 time:1470270029 size: 998219 Tx:516 Sig:3264
2016-08-04 00:20:45 Pre-allocating up to position 0x6000000 in blk00588.dat
2016-08-04 00:20:47 UpdateTip: new best=000000000000000000cb6f0ed5e09a91381235f03b73091b1447d257d8f5cb64  height=423562  log2_work=85.081202  tx=146833278  date=2016-08-04 00:20:29 progress=1.000000  cache=146.6MiB(76272tx)
2016-08-04 00:20:53 Acceptable block: ver:20000000 time:1470270044 size: 13804 Tx:49 Sig:79
2016-08-04 00:20:53 UpdateTip: new best=0000000000000000044160b65a162edb4f3488e7afd588147086df49fe6ad134  height=423563  log2_work=85.081232  tx=146833327  date=2016-08-04 00:20:44 progress=1.000000  cache=146.6MiB(76314tx)
2016-08-04 00:26:05 Acceptable block: ver:20000000 time:1470270323 size: 997171 Tx:664 Sig:1090
2016-08-04 00:26:07 Pre-allocating up to position 0xb00000 in rev00588.dat
2016-08-04 00:26:07 UpdateTip: new best=0000000000000000011b977e80b2d0ba36980e9f6caf3f3fc867ebf74f9da255  height=423564  log2_work=85.081263  tx=146833991  date=2016-08-04 00:25:23 progress=1.000000  cache=149.9MiB(79903tx)
2016-08-04 00:35:00 Node 52.58.239.112:33490 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:37:21 Acceptable block: ver:20000000 time:1470271017 size: 988659 Tx:1529 Sig:7283
2016-08-04 00:37:21 UpdateTip: new best=0000000000000000006b98dead3d1ea95c6f4d54c20799a6d13a809743bad069  height=423565  log2_work=85.081294  tx=146835520  date=2016-08-04 00:36:57 progress=1.000000  cache=152.0MiB(82005tx)
2016-08-04 00:41:35 Node 98.211.233.23:59903 socket recv error 'Connection reset by peer (104)'
2016-08-04 00:56:18 Acceptable block: ver:20000000 time:1470272163 size: 998113 Tx:2135 Sig:3313
2016-08-04 00:56:18 UpdateTip: new best=000000000000000003b3fead81c7096261752b81358a1c06af3b42d9c682144a  height=423566  log2_work=85.081324  tx=146837655  date=2016-08-04 00:56:03 progress=1.000000  cache=153.3MiB(85589tx)
2016-08-04 07:49:05 tor: Thread interrupt
2016-08-04 07:49:05 torcontrol thread exit
2016-08-04 07:49:05 opencon thread interrupt
2016-08-04 07:49:05 addcon thread interrupt
2016-08-04 07:49:05 scheduler thread interrupt
```

**Comment by ptschip** [comment] 2016-08-05 03:45
what happens when you try to restart?

**Comment by bitkevin** [comment] 2016-08-06 13:45
@ptschip CPU 100% so I have to kill it using `kill -9`.

**Comment by ptschip** [comment] 2016-08-06 13:58
were you in the process of syncing the chain by any chance or was the node already caught up and just processing tx's and new blocks?

BTW there is also another user having trouble on Ubuntu...

**Comment by bitkevin** [comment] 2016-08-06 14:35
no, not syncing blocks, it has catch up the latest height for a long time.

We will give you more information when it happened again.

**Comment by ptschip** [comment] 2016-08-06 16:36
Looks like we have two other people also reporting issues on Ubuntu...one is on Vultr, Storage node, Ubuntu 14.04 x64.  I think Core 12.1 also has reported issues with Ubuntu.

We're currently waiting for another user to provide a backtrace the next time it happens and hopefully we'll get to the bottom of it.  

So far no reports of any issues on Windows or the Linux versions.

**Comment by ptschip** [comment] 2016-08-08 02:59
are you running this on your home computer or on a VPS?

**Comment by bitkevin** [comment] 2016-08-08 18:29
yes, on VPS

**Comment by ptschip** [comment] 2016-08-08 20:43
looks like all our crashes are on ubuntu 14.04 VPS.

could you try running with the following settings in bitcoin.conf:

maxmempool=100
use-thinblocks=0

i think it might shed some light .

and then let me know if you get another crash
thanks

**Comment by ptschip** [comment] 2016-08-08 20:48
can you also run:

```
 cat /etc/lsb-release
```

and tell me exactly what it says...thanks

**Comment by mmouse-** [comment] 2016-08-15 15:51
Just wanted to confirm that I have exactly the same problem with two nodes running on Debian Jessie. Both are x64 VPS boxes, one with kernel 2.6.32-042stab113.11 (openvz), one with kernel 3.16.0-4-amd64 (debian stock kernel).

strace showed endless lines of
`clock_gettime(CLOCK_REALTIME, {1471276156, 446477646}) = 0
futex(0x1324604, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34407, {1471276156, 646477646}, ffffffff) = -1 ETIMEDOUT (Connection timed out)`
and nothing else. 

Unfortunately I restarted both nodes before finding this bug report, so I can't provide more detailed logs as of now.

I didn't get this kind of hang/deadlock with version 0.12.0

**Comment by ptschip** [comment] 2016-08-20 13:41
The bugfix release was just posted and new binaries are available from the BU website.

**Comment by nshopik** [comment] 2016-08-28 19:59
I never seen problems with 0.12.0 but 0.12.1 often eat cpu core and locks.

**Comment by ptschip** [comment] 2016-08-28 22:01
@nshopik grab the new bugfix release from the bu website.  that problem was fixed, you probably have the previous 12.1 running.

**Comment by nshopik** [comment] 2016-08-29 08:20
@ptschip Thanks, you should make more clear version numbering. Just give it something like 0.12.1a or something to avoid confusion. At least in future if it happens to have another quick fix release.

**Comment by vergecurrency** [comment] 2016-09-09 00:46
@ptschip could you please tell me which commit specifically fixed this? and was it only related to 14.04 on 64 bit? i see it was affected on machines with different kernels.

**Comment by ptschip** [comment] 2016-09-09 01:32
@vergecurrency  sorry i don't have time to look up the commit, but i believe it was an iterator going out of bounds.  It was not specific to 14.04 but for some reason Windows would handle it gracefully...anyway it's fixed and you can grab it from the new 12.1 up on the website.

**Comment by sickpig** [comment] 2016-09-21 08:38
@vergecurrency have you been able to reproduce the hang with the last available binaries from the bitcoinunlimited.info web site?

**Comment by sickpig** [comment] 2016-10-11 09:02
I think we could close this issue, unless @vergecurrency did manage to reproduce the hang with current stable release (0.12.1c)

**Closed as completed** 2016-10-17 05:39 UTC
