### ISSUE TITLE
Blk file storage does not operate on an append-only basis

### ISSUE THREAD

**Issue by TierNolan** [gandrewstone/bitcoin#1502] opened 2018-11-29 00:57 UTC
Saving to blk*****.dat files should operate on an append-only basis.  

At the moment, Bitcoin Unlimited writes new blocks to the first blk*****.dat file that has space (and then doesn't check any files before that until the next restart).  This means that it will write to space left in historical blk files.

I suspect that it will degrade performance of pruning, but perhaps not excessively.  Pruning is most optimal if blocks of around the same date are all stored together.

The problem is caused by not initializing the nLastBlockFile global variable.

Originally, when the code was in main.cpp, it was initialized by [this line](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/bucash1.2.0.1/src/main.cpp#L4515).
    
    pblocktree->ReadLastBlockFile(nLastBlockFile);
    
The ReadLastBlockFile(...) method sets the passed reference to the value stored in the database.

The new code has [this line](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/src/blockstorage/blockstorage.cpp#L318).
    
    int loadedblockfile = 0;
    pblocktreeother->ReadLastBlockFile(loadedblockfile);
    
This means that the global variable is not set (and stays at its default value of zero).

This is what causes the node to go back and add blocks to old blk*****.dat files that are historical.

The effect can be demonstrated by restarting the node and then sorting the blk*****.dat by date after a few blocks have been found.  The new blocks won't be written into the latest block file.

It is most obvious on nodes after a full resync, but I suspect it will remain for a while on all nodes.  As spaces are filled-in, the effect will occur less for older files.

I discuss the issue more on the forums in [this thread](https://bitco.in/forum/threads/question-about-updates-to-blk-files.23053/#post-84678).

**Comment by sickpig** [comment] 2018-11-29 13:35
Thanks @TierNolan for opening the issue. Will look into that. @Greg-Griffith was the last one who touched that part of the code, maybe he could have a clearer idea of what's happening here.

**Comment by Greg-Griffith** [comment] 2018-11-29 15:28
@TierNolan i looked into your issue and it seems you are just looking at the wrong part of the code. The code you found was for syncing between different storage methods (changing from leveldb to blk files and vise versa) since we support more than one. 

loadedblockfile is used inside SyncStorage() which is called [here](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/src/validation/validation.cpp#L343) and is thrown away at the end of the method. the global variable nLastBlockFile is initialized about 100 lines later [here](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/src/validation/validation.cpp#L447)

(posted same response on the forums in your thread)

**Comment by TierNolan** [comment] 2018-11-29 23:59
Fair enough, I was mostly reporting the unusual behavior. The issue still exists though.  

Having another look at the code, I think it is the other side of the persistence sequence that is at fault.  The variable isn't written to the database at all, so even if initialized from the database, it still stays at 0 on restart.

In [this commit](https://github.com/BitcoinUnlimited/BitcoinUnlimited/commit/43aa7a05327acd2e4c5415d6b3779f0c154783d1#diff-81e4f16a1b5d5b7ca25351a63d07cb80L232), the write DB_LAST_BLOCK is deleted.

If you checkout the commit, you can see that it is only used to write to the database.
    
    git checkout 43aa7a05327acd2e4c5415d6b3779f0c154783d1
    grep -r DB_LAST_BLOCK .
    

The above grep gives this output.
    
    ./src/txdb.cpp:static const char DB_LAST_BLOCK = 'l';
    ./src/txdb.cpp:bool CBlockTreeDB::ReadLastBlockFile(int &nFile) { return Read(DB_LAST_BLOCK, nFile); }
    

If I go back one commit, then it appears
    
    git checkout HEAD~1
    grep -r DB_LAST_BLOCK .

The grep gives this output.
    
    ./src/txdb.cpp:static const char DB_LAST_BLOCK = 'l';
    ./src/txdb.cpp:bool CBlockTreeDB::ReadLastBlockFile(int &nFile) { return Read(DB_LAST_BLOCK, nFile); }
    ./src/txdb.cpp:    batch.Write(DB_LAST_BLOCK, nLastFile);
    

The commit 43aa7a05327acd2e4c5415d6b3779f0c154783d1 deleted the write of the variable to the database.

**Comment by Greg-Griffith** [comment] 2018-11-30 01:00
ah yep. seems that is the issue. i will fix that. thanks for finding it and reporting it

edit: #1504 will fix this issue once merged

**Comment by sickpig** [comment] 2018-11-30 08:20
@TierNolan thanks for finding the root cause of the issue. 
@Greg-Griffith thanks for providing the fix #1504 so quickly.

**Comment by TierNolan** [comment] 2018-11-30 19:08
Glad to see it fixed.  I suspect that it could have caused problems / less efficient pruning and it does cause some difficulties with maintaining Bitcoin Armory compatibility.

**Comment by sickpig** [comment] 2018-12-05 14:06
@TierNolan Greg's #1504 got merged and will be available soon in 1.5.1.0
Closing the issue, please reopen it you think we need to discuss further.

**Closed as completed by sickpig** 2018-12-05 14:06 UTC
