### ISSUE TITLE
abandonconflict.py randomly fails on 'dev' and 'release' branches 

### ISSUE THREAD

**Issue by ftrader** [gandrewstone/bitcoin#537] opened 2017-05-07 17:57 UTC
This test fails randomly. Results of repetitive testing for 'abandonconflict.py' on Debian 7 x86_64 native:

'dev' branch: 43/100 failed
'release' branch: 42/100 failed

Release tag v1.01.4 : also fails 2/10 
Release tag 1.0.1.3 tested ok - 10/10 PASS 

On Ubuntu 16.10: 57/100 failed on 'dev'. Didn't bother to run repetivite on 'release', went straight for a bisection using the bisect.sh script from https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/532 .
Command was:
`git bisect run bisect.sh 20 300 'qa/pull-tester/rpc-tests.py abandonconflict'` (with 20 iterations, 300s timeout and RECONFIGURE_BETWEEN_RUNS=1). Starting commit (bad revision) was e78ce5ee786d15136c30a00dc2e13a8847b361ce , good revision (through manual test above) was 1.0.1.3
Result:
`first bad commit: [4e55fdde78e3406aa02d535fd928e3fa5fac4f72] Disconnect and ban a node if they fail to provide the inital HEADERS` 

A bisection for 'dev' is still in progress.

**Comment by ptschip** [comment] 2017-05-07 18:17
@freetrader  sounds like you might have a timing issue...initial headers
need to come back within 30 seconds..you might want to try 60 and see if
the problem goes away.  (just fyi, i never have any issues running this
test on my system)

got ot line 116 main.h and make INITIAL_HEADERS_TIMEOUT = 60;

perpahs even try 600 just to see if the problem is the timout period.

**Comment by ftrader** [comment] 2017-05-07 18:32
@ptschip : [Travis also has a problem](https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/532#issuecomment-299671775) with this test (this is how I initially noticed this test not passing well).

My system is old, but I'm pretty sure it's not THAT slow that it can hardly run a Bitcoin regression test :-)

I'll try to confirm though whether it's entirely timeout related. Thanks for the hint.

**Comment by ftrader** [comment] 2017-05-07 19:34
Example failure on 'dev' from ongoing bisection:

```
JSONRPC error: non-JSON HTTP response with '503 Service Unavailable' from server
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/test_framework.py", line 184, in main
    self.run_test()
  File "/home/ftrader/bu/qa/rpc-tests/abandonconflict.py", line 27, in run_test
    sync_mempools(self.nodes)
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/util.py", line 170, in sync_mempools
    pool = set(rpc_connections[0].getrawmempool())
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/coverage.py", line 51, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/authproxy.py", line 156, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/authproxy.py", line 135, in _request
    return self._get_response()
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/authproxy.py", line 179, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
Stopping nodes
Traceback (most recent call last):
  File "/home/ftrader/bu/qa/rpc-tests/abandonconflict.py", line 157, in <module>
    AbandonConflictTest().main()
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/test_framework.py", line 203, in main
    stop_nodes(self.nodes)
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/util.py", line 376, in stop_nodes
    node.stop()
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/coverage.py", line 51, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/authproxy.py", line 156, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/ftrader/bu/qa/rpc-tests/test_framework/authproxy.py", line 134, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/home/ftrader/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/home/ftrader/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/home/ftrader/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/home/ftrader/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/ftrader/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/ftrader/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/ftrader/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/home/ftrader/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by ftrader** [comment] 2017-05-07 20:29
Bisection result from 'dev' on Debian 7 native: 1df110e02cfb4643fc61d74636cdd8968f827e62 is the first bad commit 
(same principal change as on 'release')
Bisection log:
```
$ git bisect log
# bad: [9d85241826f2521eec56b5d95f6b009bdf260eb5] Merge pull request #525 from kyuupichan/exp-unify
# good: [0824e741b3ed47a689ae4490b4206dda378da7ef] Improve tor documentation
git bisect start 'HEAD' '0824e741b3ed47a689ae4490b4206dda378da7ef'
# bad: [8708ac1bde8fe3bf8129b96af7050601723df962] Merge #9008: [net] Remove assert(nMaxInbound > 0)
git bisect bad 8708ac1bde8fe3bf8129b96af7050601723df962
# bad: [2982f4753f953a250b5e8b9ed7e4a36a504df6b5] Merge pull request #422 from AllanDoensen/devGuiFix
git bisect bad 2982f4753f953a250b5e8b9ed7e4a36a504df6b5
# bad: [b0790846dd08509f308e1e135f41d29b8f2aca14] Merge pull request #401 from gandrewstone/block_sync_polling_loop
git bisect bad b0790846dd08509f308e1e135f41d29b8f2aca14
# good: [fccefa5b2eaa5625547c8ebc58cd19e14672c154] Remove BU-specific alert system bits
git bisect good fccefa5b2eaa5625547c8ebc58cd19e14672c154
# good: [87392b448973b284d05400ef778023f288d6fee0] Merge pull request #360 from kyuupichan/remove-alerts
git bisect good 87392b448973b284d05400ef778023f288d6fee0
# bad: [101502f859321be2fbd5c5bd29bfa539ba88a911] Merge pull request #356 from ptschip/dev_sync
git bisect bad 101502f859321be2fbd5c5bd29bfa539ba88a911
# good: [0ba700c6b22a83d5961106ebd4d62a2b3f38c1d5] Merge pull request #351 from ptschip/dev_ui
git bisect good 0ba700c6b22a83d5961106ebd4d62a2b3f38c1d5
# bad: [1df110e02cfb4643fc61d74636cdd8968f827e62] Disconnect and ban a node if they fail to provide the inital HEADERS
git bisect bad 1df110e02cfb4643fc61d74636cdd8968f827e62
# first bad commit: [1df110e02cfb4643fc61d74636cdd8968f827e62] Disconnect and ban a node if they fail to provide the inital HEADERS
```

**Comment by gandrewstone** [comment] 2017-05-08 17:22
The problem is that a node makes a HEADERs request, and the other node must respond or get booted.

But GETHEADERs does not always respond.  For example:
        
if (IsInitialBlockDownload() && !pfrom->fWhitelisted) {
            LogPrint("net", "Ignoring getheaders from peer=%d because node is in initial block download\n", pfrom->id);
            return true;
        }

We must either ensure that GETHEADERs always responds (in all clients) or remove this check.

**Comment by ptschip** [comment] 2017-05-08 17:32
has anyone tried just whitelisting the nodes during the tests?

**Comment by gandrewstone** [comment] 2017-05-08 18:18
while whitelisting may work, on the real network we will still be kicking legit nodes out

**Comment by ptschip** [comment] 2017-05-08 19:14
on the real network we don't ban a node , unless they claim their chain
height is longer than ours AND we tried to getheaders from them to sync
our own chain.  So we
would never ban a node if for instance they were doing IBD and couldn't
provide us the headers anyway.

on the other hand, i think you might be partly right here,  in one
special case, if they are also doing IBD at the same time we are AND are
ahead of us, then we could potentially get into a ban...so perhaps we
need to instead issue a disconnect, instead of ban, so that we can
continue our IBD and get headers from the next node and also give the
other node a chance to reconnect later.  And it would be safer anway...a
disconnect here is enough.

but all that said, it won't fix the problem with this script...i still
think the only solution for this script may be to whitelist.

**Comment by ftrader** [comment] 2017-05-08 19:31
With whitelisting the test passed 16 times in a row (on dev @ 73a9cfebb0d01eb84554aee13c2c065be27f178a) , then it failed on iteration 17 failed with a '503 Service Unavailable' error after being timed out (I set it to 300s - the test usually takes 120-140s when it passes).

**Comment by ftrader** [comment] 2017-05-09 14:14
Decided to whitelist this test as it does not interfere with the functionality tested.
The remaining timeout problem is something which apparently randomly affects multiple tests - seems a separate problem.

**Comment by sickpig** [comment] 2017-05-11 22:49
@ftrader test pass for me 10 times in a row bot on current `dev` and `release`.

**Comment by ftrader** [comment] 2017-05-12 06:22
@sickpig : Did another test run on current 1.0.2.0 release (9fcdbf50585744696c74c162398cea4f026efda4) and it timed out again on run 17.
```
Random seed: 1494567800
Initializing test directory  /tmp/testxzxvr2n4 Bitcoin conf:  None walletfiles:  None
[202, 300]
[210, 300]
[218, 300]
[239, 300]
[300, 300]
Unexpected exception caught during testing: timeout('timed out',)
Stopping nodes
Cannot send request: Request-sent
Connection broken:  [Errno 32] Broken pipe
Cleaning up
Failed
Running testscript ESC[1mabandonconflict.pyESC[0m ...
CalledProcessError for test abandonconflict: Command '/home/ftrader/bu/qa/rpc-tests/abandonconflict.py --srcdir /home/ftrader/bu/src  ' returned non-zero exit status 1
Duration: 70 s
```

On current 'dev' (76fd9a67db5ccac0ec9a05a89299496731684264) I had a pass rate of 17 / 20 .
First failure (little bit different than on 'release'):
```
[301, 301]
JSONRPC error: Node not found in connected nodes
Stopping nodes
Cleaning up
Failed
```

and two seemed to have failed with
`JSONRPC error: non-JSON HTTP response with '503 Service Unavailable' from server`

So unfortunately I don't think this problem has really been fixed on current 'dev' / 'release' .

**Comment by sickpig** [comment] 2017-05-14 23:33
@ftrader 

tested `release` @ 9fcdbf5 40 times in a row in 2 different systems and I didn't get any failures.

tested also `dev` @ 76fd9a67 30 times still no failures.

Tomorrow I'll try to test with a higher numbers of retries.

**Comment by ftrader** [comment] 2017-05-15 17:29
Noticed https://github.com/bitcoin/bitcoin/pull/10344 .

I will try the approach taken there.

**Comment by ptschip** [comment] 2017-05-15 17:35
looks good, that connect node bi thing is pretty crazy, i never
understood why they introduced that in the first place.

**Comment by ftrader** [comment] 2017-05-15 17:53
Raised https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/582 , but am doing some more repetitive testing on my system to get a feel for whether it's effective for me.

**Comment by sickpig** [comment] 2017-08-14 13:29
`abandonconflict.py` does not fail on a series of 80 retries in a row, both on `release` and `dev` branches. 

Closing, @ftrader please feel free to reopen if you are able to reproduce the problem.

**Closed as completed by sickpig** 2017-08-14 13:29 UTC
