### ISSUE TITLE
Issue compiling on FreeBSD 10

### ISSUE THREAD

**Issue by Atraps003** [gandrewstone/bitcoin#304] opened 2017-02-16 21:32 UTC
Gmake fails with the following error.

  CXX      leveldb/db/leveldb_libleveldb_a-builder.o
<command-line>:0:13: warning: ISO C99 requires whitespace after the macro name
In file included from ./leveldb/port/port.h:14:0,
                 from ./leveldb/db/filename.h:14,
                 from leveldb/db/builder.cc:7:
./leveldb/port/port_posix.h:38:22: fatal error: endian.h: No such file or directory
   #include <endian.h>
                      ^
compilation terminated.
gmake[2]: *** [Makefile:3874: leveldb/db/leveldb_libleveldb_a-builder.o] Error 1
gmake[2]: Leaving directory '/usr/src/bu-src/src'
gmake[1]: *** [Makefile:8239: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/src/bu-src/src'
gmake: *** [Makefile:652: all-recursive] Error 1

**Comment by kyuupichan** [comment] 2017-03-06 21:33
Can you try #345 please?

**Comment by ftrader** [comment] 2017-03-19 23:32
FYI: the https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/345 patch helped someone to get past this problem on FreeBSD 11 as well.

https://np.reddit.com/r/btc/comments/609lfn/bu_on_freebsd_11/df53dsf/

**Comment by kyuupichan** [comment] 2017-03-20 05:22
@gandrewstone Perhaps we can close this one then?

**Comment by ftrader** [comment] 2017-03-20 20:10
Given some time, I can try to check on a FreeBSD 10 VM.
Would be premature to close it imo if the issue is raised for 10.

**Comment by Atraps003** [comment] 2017-03-23 02:54
#345 resolved the issue for me on FreeBSD 10.

**Closed as completed** 2017-03-23 02:57 UTC
