### ISSUE TITLE
dbcache default of 500MB not being honoured

### ISSUE THREAD

**Issue by ptschip** [gandrewstone/bitcoin#932] opened 2018-01-22 16:19 UTC
A user complained that they had a dbcache of 300MB however the default minimum is 500MB.  The user did not have a bitcoin.conf file so the values must have been pulled from QT and were incorrect for some reason.  Possibly these were being carried over from a past version of BU where the default value was 300MB.  We should review how QT working here in terms of keeping/setting these config values.  Seems like a potential bug here.

**Comment by sickpig** [comment] 2018-05-25 07:29
Closing in light of #948 and various changes in that area. 

@ptschip feel free to reopen I case you think the issue is till unsolved.

**Closed as completed by sickpig** 2018-05-25 07:29 UTC
