### ISSUE TITLE
Warning: Unknown block versions being mined! It's possible unknown rules are in effect

### ISSUE THREAD

**Issue by romanrm** [gandrewstone/bitcoin#721] opened 2017-08-02 19:44 UTC
This warning is shown by the BUcash release for the post-fork Bitcoin Cash blocks. As I was specifically downloading the Bitcoin Cash release I'd expect it to "know" about its block versions and rules, but it appears it doesn't? Is it even safe to use at all?

**Comment by snavsenv** [comment] 2017-08-03 02:35
BU is not safe to use.

**Comment by sickpig** [comment] 2017-08-03 21:07
@romanrm 
block 478561 ver was 0x20000002, hence signalling SegWit. 
https://blockchair.com/bitcoin-cash/block/478561

**Comment by gandrewstone** [comment] 2017-08-04 13:09
as sickpig suggests the code is seeing the various segwit bits as unknown since segwit activation is not defined on BCC.  However, we will likely identify this bit in the next release so that the message goes away.

Readers: look at who clicked the thumbs up button (hover over it) in the 2nd comment.  I guess he has nothing better to do than troll our bugs... :-)

**Comment by romanrm** [comment] 2017-08-04 15:47
> we will likely identify this bit in the next release so that the message goes away.

Thanks!

**Comment by dgenr8** [comment] 2017-08-04 16:43
@gandrewstone Why do that, unless you are actually going to implement segwit and define a bip9 deployment for it?  The notice that miners are setting a version bit the software doesn't understand is correct.

**Comment by gandrewstone** [comment] 2017-08-04 17:22
the software understands it as being a bit irrelevant to bitcoin cash...

**Comment by sickpig** [comment] 2017-09-07 12:39
closing, fixed in the latest release of BUcash.

**Comment by pffff** [comment] 2018-03-02 07:43
so why is it still showing the warning, am just syncing with latest version 1.2.0.1 and it is showing this warning now

**Comment by pffff** [comment] 2018-03-02 07:50
so why is it still showing the warning, am just syncing with latest version 1.2.0.1 and it is showing this warning now

**Comment by sickpig** [comment] 2018-03-02 09:26
@pffff 

what do you mean with just syncing? are you performing initial block downloads (IBD)?

**Comment by pffff** [comment] 2018-03-02 09:29
yes, 
![image](https://user-images.githubusercontent.com/5829016/36892350-bded00c0-1e04-11e8-9740-e2225b7a8763.png)

**Comment by sickpig** [comment] 2018-03-02 09:36
ok thanks for the heads up. so you are definitely in IBD. 

this is rather strange thou cause the display of the warning should be disabled during IBD. 

see: https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/bucash1.2.0.1/src/main.cpp#L2754

going to try to reproduce it here.

**Comment by pffff** [comment] 2018-03-02 09:38
fyi it was not showing the warning until it reached block somewhere in July 2017 (dont remember the exact blocknumber), it was also after I restarted the client (dont know if that has to do with it)

**Comment by sickpig** [comment] 2018-03-02 09:39
just one more thing: 

try to execute `getinfo` from the debug window and paste the result here.

**Comment by pffff** [comment] 2018-03-02 09:41
i restarted the client, and the warning is gone...
{
  "version": 1020001,
  "protocolversion": 80003,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 501659,
  "timeoffset": 21,
  "connections": 12,
  "proxy": "",
  "difficulty": 113081236211.4533,
  "testnet": false,
  "keypoololdest": 1519581599,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "status": "ready",
  "errors": "",
  "fork": "Bitcoin Cash"
}

`

**Comment by sickpig** [comment] 2018-03-02 09:45
I guess that the problem is related to the fact that the GUI state was not
updated and the warning that came from before Aug 1st (day of the fork) and
it was therefore legit get stuck to the notification are and wasn't not
cleared after the fork.

Going to have a look a the code to make it not happen again.

**Comment by sickpig** [comment] 2018-03-02 14:01
re-opening, issue is still present on 1.2.0.1

**Comment by ptschip** [comment] 2018-03-02 15:11
what we really need is only show the warning when we're not in initial syncs so we need a 

       if (!IsInitialBlockDownload())

before showing the warning.

**Comment by ptschip** [comment] 2018-03-02 15:24
@pffff hmm...the code actually has that in there so that the warning is not triggered during initial sync...so what has probably happened in this case (what must have happened)  is that your node accidentally triggered the end of IBD.  This can only happen (that i'm aware of) if at some point your blocks were processed very close to where your best header was...and this could only happen during the very initial phase of block download where we download the headers.  Your node must have stopped downloading the initial headers for a few seconds while the blocks got connected all the way to it's current best header...and then the remaining headers got downloaded after.

Can you do something, can you restart your node and then see if the warning is cleared?  When you restart, the isinitalblockdownload flag will be reset to true should prevent the warning from coming up.  If not, then there is some other issue i'm not aware of.

**Comment by pffff** [comment] 2018-03-03 00:19
@ptschip yes the warning went away after I restarted. This is what happened: I was performing IBD, after a couple days I decided to quit the client and turn of the computer and continue later, when I continued the warning showed up, so if what you say happened, it happened then. After a while I restarted again and the warning went away.

**Comment by sickpig** [comment] 2018-03-05 14:27
the warning should not happen in the first place as @ptschip  [said](https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/721#issuecomment-369951235)

but I wonder if we could somehow "ameliorate" the situation if we clear the warning in case the condition that triggered it is not valid anymore, something like #993

**Comment by sickpig** [comment] 2018-05-25 07:38
#993 has been merged, closing

**Closed as completed by sickpig** 2018-05-25 07:38 UTC

**Comment by bill-mcgonigle** [comment] 2019-05-09 01:54
In case somebody else hits this (I just did on  bucash1.6.0.0 (64-bit)) ... I think what happened is that Core got launched as another user and (I am supposing) that it got some packets out before it failed to bind a socket to listen, and so then some data came back on the port BU was already listening on, probably with segwit, triggering the warning.

So, probably #stupidusertricks , not a bug in my case.

**Comment by ptschip** [comment] 2019-05-09 02:08
that message will come and go...it's related to wormhole and the bits
that they're signalling...we'll have to look at bypassing that somehow. 
thanks for the report though, no need to worry.
