### ISSUE TITLE
Pruning leaves too many blocks on disk

### ISSUE THREAD

**Issue by davidebaldini** [gandrewstone/bitcoin#285] opened 2017-02-06 23:03 UTC
With `prune=600` the node stores about 30 GB of blocks on disk.

I installed BU on a clean Debian environment, on the newly-created `bu` home folder:

    bu@hwcharts:~$ wget 'https://www.bitcoinunlimited.info/downloads/bitcoinUnlimited-1.0.0-linux64.tar.gz'
    bu@hwcharts:~$ tar -axf bitcoinUnlimited-1.0.0-linux64.tar.gz

and I created `bitcoin.conf`before starting the client even once; it contains:

    bu@hwcharts:~$ cat .bitcoin/bitcoin.conf
    prune=600
    excessiveblocksize=1000000
    excessiveacceptdepth=12

then I started the client:

    bu@hwcharts:~/bitcoinUnlimited-1.0.0/bin$ ./bitcoind --version
    Bitcoin Unlimited Daemon version v1.0.0.1-b471620

    bu@hwcharts:~/bitcoinUnlimited-1.0.0/bin$ nohup ./bitcoind &
    
and for two days the size of `~/.bitcoin` kept rising up to 40 GB until block synching completed: (100% = 100 GB)
![disk_usage](https://cloud.githubusercontent.com/assets/8339909/22669612/c5e1c944-ecc5-11e6-9c7a-5add79a420c6.png)

then I stopped the BU client with an unpolite `pkill bitcoind`, but `~/.bitcoin/debug.log` recorded a smooth shutdown:

    2017-02-06 22:26:03 UpdateTip: 30 of last 100 blocks have unexpected version. One example: 0x20000002
    2017-02-06 22:26:21 tor: Thread interrupt
    2017-02-06 22:26:21 torcontrol thread exit
    2017-02-06 22:26:21 msghand thread interrupt
    2017-02-06 22:26:21 opencon thread interrupt
    2017-02-06 22:26:21 addcon thread interrupt
    2017-02-06 22:26:21 scheduler thread interrupt
    2017-02-06 22:26:21 net thread interrupt
    2017-02-06 22:26:21 Shutdown: In progress...
    2017-02-06 22:26:21 StopNode()
    2017-02-06 22:26:21 Shutdown: done

then I restarted the client from the same path and with the same command as before. After the client restarted, the following was appended to the end of `debug.log`: https://pastebin.mozilla.org/8974271, and the disk usage inside `~/.bitcoin` was

    bu@hwcharts:~/.bitcoin$ du -h
    1.9G    ./chainstate
    67M     ./blocks/index
    27G     ./blocks
    29G     .

### System details:

    bu@hwcharts:~/.bitcoin$ uname -a
    Linux hwcharts 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 i686 GNU/Linux

    bu@hwcharts:~$ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/simfs      100G   37G   64G  37% /
    tmpfs           205M   60K  205M   1% /run
    tmpfs           5.0M     0  5.0M   0% /run/lock
    devtmpfs         10M     0   10M   0% /dev
    tmpfs           410M     0  410M   0% /run/shm

    bu@hwcharts:~/.bitcoin$ free
                 total       used       free     shared    buffers     cached
    Mem:       2097152     446380    1650772          0          0     198332
    -/+ buffers/cache:     248048    1849104
    Swap:            0          0          0

    bu@hwcharts:~/.bitcoin$ cat /etc/debian_version
    8.6

**Comment by ftrader** [comment] 2017-02-06 23:41
As a minor note, `pkill` by default sends SIGTERM unless otherwise specified, this invokes the graceful shutdown, so that consequence is not unexpected.

**Comment by ftrader** [comment] 2017-02-06 23:48
Question: are you running a wallet on that node?

**Comment by davidebaldini** [comment] 2017-02-07 00:01
I'm not passing any cli options to `bitcoind` (such as `-disablewallet`) and I didn't delete `wallet.dat` which was created automatically on the first execution, so the wallet is active by default, but I have no addresses in it.

**Comment by ftrader** [comment] 2017-02-07 00:21
Thanks, there goes my first theory then. Looks like we'll need to reproduce and see what's going on here.

**Comment by ftrader** [comment] 2017-02-07 00:59
If it's possible, can you stop the node, add `debug=prune` to your config, and restart?

That might give some more clues about what the pruning functionality is doing in this instance.
Might have to wait a while, but debug traces of this format should appear in the log output:

`Prune: target=%dMiB actual=%dMiB diff=%dMiB max_prune_height=%d removed %d blk/rev pairs`

**Comment by davidebaldini** [comment] 2017-02-07 01:26
I added `debug=prune` and restarted `bitcoind` exactly as before. This is the log since restart:

https://pastebin.mozilla.org/8974323

**Comment by macleana** [comment] 2017-02-08 14:01
I'm encountering a similar issue during syncing, the 20GB drive is not allowing for graceful syncing. It got halted over night, I reduced pruning from 15000 to 10000, freed up some disk space and bitcoind is just using up whatever space it can and is slowly closing in on my remaining disk space as it continues syncing.

My installation followed the procedure found here: https://keepingstock.net/how-to-create-a-bitcoin-unlimited-full-node-on-a-hosted-server-5bc858a614e3#.97vmfhiyk

Here's my pruning related logs:
https://pastebin.mozilla.org/8977709

**Comment by ftrader** [comment] 2017-02-08 14:28
@macleana : was your node (originally with pruning to 15000) busy syncing from scratch too?

**Comment by macleana** [comment] 2017-02-08 14:52
@ftrader : It should of had been syncing from scratch. I recently got the VPS solely to turn it into a BU node and didn't download the blockchain or anything beforehand. I recall that when I started up bitcoind for the first time, I found it odd the first block count I saw some time later was somewhere in the 200k, it would make sense if some of the earlier blocks are considerably smaller though.

At the time of lowering the pruning value, the daemon had exited beforehand due to the disk being full, and I'm pretty convinced it's about to exit again soon, despite the even stricter pruning value.

**Comment by ptschip** [comment] 2017-02-08 15:01
when the disk was full the first time and bitcoind exited...we're you
able to restart without doing anyting to the disk space?  by that i
mean, when you lauch bitcoind did it then initially prune the blockchain
to the correct size  and continue again, only to stop pruning later when
the disk was again full?   The reason I ask is that i run a pruned
node...when i installed a copy of the blockchain and then ran bitcoind
for the first time, the blockchain was initally pruned to the correct
size...

**Comment by ftrader** [comment] 2017-02-08 15:11
@ptschip : I tried the 'pruning from a full blockchain' today, using both  BU 1.0.0.1 and Core 0.12.1.

I put prune=600 but in both cases they pruned it down to only 3.5GB in blocks/ .
Now that is way less than the submitters in this report are seeing on their nodes, but it's still unexpected (at least to me). I thought there is a strict limit (288 blocks) plus maybe 17MB of buffer space or something that must be retained at all costs - the documentation states ~550MB .

So it looks like there is definitely something wrong with the pruning, and it seems to be even worse when synching an empty node. I'm going to try that locally with some instrumented binaries to get a better idea of what's going on.

A pruned node I've inspected (50GB) has not shown any problems recently, despite I upgraded to BU 1.0.0.1 as well.

**Comment by ptschip** [comment] 2017-02-08 15:21
my understanding of pruning is that anything above 550 blocks in your
config is treated as MB...kind of strange that it's like that, but maybe
it doesn't really work...so I have 10000, which should be 10gb and
indeed it's close to that but not 10gb, it's 9.7 gb, but 10, 435, 514
bytes on disk...

**Comment by macleana** [comment] 2017-02-08 15:23
@ptschip : I was not able to relaunch bitcoind after it had stopped without freeing up some disk space. I was getting an error specific to accessing the local block files and a lack of disk space when I tried to relaunch bitcoind. I had an unused swap file that I deleted to free up some space.

I'm certain that upon launching bitcoind there was no trimming of the local block chain to the pruning value, if even any trimming at all.

My disk space got used up again, I'm now reindexing, hoping for the best.

`bitcoin-cli getinfo
{
  "version": 1000001,
  "protocolversion": 80002,`

`Linux vps 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Thanks! Hope this helps.

**Comment by ftrader** [comment] 2017-02-09 00:53
It looks like this problem is the result of some longstanding bugs ~~with the pruning which have not been fixed in Core either.~~

EDIT: it does not appear that Core versions are affected by this - at least not 0.12.x and 0.13.x .

Fixes incoming courtesy of @ptschip : https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/291

Those patches seem to be doing well in our preliminary internal testing - those of you here who are running nodes compiled from source might want to apply them, test and report back your results...

**Comment by ftrader** [comment] 2017-02-09 20:34
Further to my last post - lead dev has changed that code fix to Work in Progress, and there are some different approaches being tried, so perhaps best to hold off unless you feel like testing very experimental fixes.

Due to the long test times on the synching operations, this could take a few days to get to a patch that the devs agree is stable / complete enough.

**Comment by sickpig** [comment] 2017-02-16 17:48
Latest version of @ptschip's PR #291 fix the problem for me.

**Comment by sickpig** [comment] 2017-02-20 11:02
@davidebaldini PR #191 has been merged onto the dev branch. 

It fixes the problem in all the the test we have done so far. 

Could please check if it fixes the problem for you? 

thanks

**Comment by davidebaldini** [comment] 2017-02-20 23:25
I won't test the BU dev branch on the same host which this bug report is based upon; I have some dependency issues on that machine which prevent me from compiling BU unless I retarget my `apt-get` to Debian Testing.

I [shared](http://75.127.3.156/bitcoin.tgz) my whole `~/.bitcoin` directory as a `tar.gz` if someone has a comfortable environment where to test BU with my chain. The block files contained there are still those incorrectly-pruned ~30GB which I described above. The size of the directory has dropped slightly since my report, but apart from a few restarts of BU, I haven't touched the directory since then.

**Comment by sickpig** [comment] 2017-02-20 23:30
@davidebaldini 

if you want to I can provide to you a static build of the binaries. What's your arch? amd64?

**Comment by ptschip** [comment] 2017-02-20 23:30
you'd have to run from scratch anyway...the old files will not get
pruned until you get sufficiently ahead...but then it depends on how
much your pruning.  If you were pruning at 1GB then you might only hoave
to wait about a week or so before the old files will start get pruned
away.  It's up to you.

**Comment by davidebaldini** [comment] 2017-02-20 23:38
@sickpig yes please, a static binary will be very helpful. Arch is i686.

@ptschip It's not a problem for me to resync the chain from scratch. I thought that keeping my incorrectly pruned chain with the revised BU might provide some insight. If I'm wrong, I'll delete `~/.bitcoin` and test the new BU. I prune at 600 MB (prune=600).

**Comment by sickpig** [comment] 2017-02-20 23:44
@davidebaldini I'm on it. Just let me know what's you preferred way to share the binaries.

**Comment by davidebaldini** [comment] 2017-02-20 23:51
@sickpig I can `wget`, `scp` or `ftp` from a machine of yours, or you can publish it on Dropbox or similar.

**Edit:** or you can `scp` into 75.127.3.156. I'm passing you the credentials.

**Comment by sickpig** [comment] 2017-02-20 23:58
@davidebaldini just send me an email to sickpig <at> gmail.com and I'll send you back the link from where you would fetch the files

**Comment by davidebaldini** [comment] 2017-02-21 15:09
I tested the patched BU `bitcoind` binary provided by sickpig; I ran it upon the same `~/.bitcoin` directory as above, with the spurious ~30GB blocks. Last time I ran BU was ~10 days earlier and I kept it off since then, so the `~/.bitcoin/blocks` folder did not contain recent blocks.

I left the patched `bitcoind` running overnight until it synced completely. The directory now is:

    bu@hwcharts:~/.bitcoin$ du -h
    1.9G    ./chainstate
    236K    ./database
    69M     ./blocks/index
    607M    ./blocks
    2.5G    .

and the config is still the same:

    bu@hwcharts:~/.bitcoin$ cat bitcoin.conf
    prune=600
    debug=prune
    excessiveblocksize=1000000
    excessiveacceptdepth=12

So at first glance the patch seems to work. However I noticed some recurrent errors in the log file, like

-     ERROR: ProcessNewBlock: AcceptBlock FAILED
-     Invalid block due to bad-prevblk
-     Misbehaving: 46.4.101.137:8333 (10 -> 20)

These types of errors are repeated tens of times in the log, but they only appear after date 2017-02-21, which is when I upgraded BU with sickpig's binaries. The log file goes back to 2017-02-06.

Also I noticed multiples of this:

-     Node 105.4.59.113:30000 socket recv error 'Connection reset by peer (104)'

but their first occurrence is marked 2017-02-07, and continue up to 2017-02-21.

----

## Log files

[Full `debug.log`](https://www.dropbox.com/s/bng2mem18rfvnqh/debug.log.long?dl=1), from 2017-02-06 onward
[Short `debug.log`](https://www.dropbox.com/s/o3pu0mlgqzk9enk/debug.log.short?dl=1), from 2017-02-21 onward, containing all the activity of sickpig's `bitcoind`.

**Comment by sickpig** [comment] 2017-02-21 21:05
@davidebaldini 

Thanks for the detailed report and for having provided the debug.log files. While we are going to investigate what happened could you please  try to resync the node from scratch?

**Comment by davidebaldini** [comment] 2017-02-21 22:12
I'm resyncing from scratch. This should take about two days.

**Comment by sickpig** [comment] 2017-02-21 22:29
Thanks !

**Comment by davidebaldini** [comment] 2017-02-24 14:59
I deleted `~/.bitcoin` and resynced from scratch; this is the folder after syncing completed:

    bu@hwcharts:~/.bitcoin$ du -h
    2.2G    ./chainstate
    16K     ./database
    66M     ./blocks/index
    621M    ./blocks
    2.8G    .

The patched bitcoind seems to work. The [log file](https://www.dropbox.com/s/m8mho009ijudjel/debug.log.resync.bz2?dl=1) still contains tens of repetitions of the same errors I listed in my [previous comment](https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/285#issuecomment-281371068).

**Comment by sickpig** [comment] 2017-02-24 17:04
@davidebaldini thanks a lot for the test. Thanks to your perseverance we have discovered other things that need to be fixed, e.g. see #312

**Comment by ftrader** [comment] 2017-03-21 01:24
@davidebaldini : this pruning issue should now be included in release 1.0.1.1 .

@ptschip : I think this issue can be closed separarely from the https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/312 handled above, right? I don't see a dependency.

**Comment by sickpig** [comment] 2017-04-28 22:12
fixed in 1.0.1.1

**Closed as completed by sickpig** 2017-04-28 22:12 UTC
