### ISSUE TITLE
[BUCash v1.1.1.0] No transaction visible on the start screen

### ISSUE THREAD

**Issue by theBergmann** [gandrewstone/bitcoin#776] opened 2017-09-07 11:10 UTC
Hi, as the title says: There is no list of last transaction on the start screen of BUCash v1.1.1.0. 

Here's an screenshot:
https://imgur.com/a/tqtJK

Little idea: I run ubuntu 16.04, but to avoid issues with libre office impress I made something with the gui, which is now windows-like. However, the issue is just with BUcash, not with ABC nor with btc1

**Comment by theBergmann** [comment] 2017-09-07 11:15
updated to 1.1.1.1, issue is still here

**Comment by sickpig** [comment] 2017-09-07 11:51
is the amount reported by the wallet correct? 
is your bitcoin-qt synced? 
next step is looking at your `debug.log` 
paging @gandrewstone @ptschip

**Comment by theBergmann** [comment] 2017-09-07 12:41
yes, amounts are correct, it is just an optical bug.

As I said, I made something to solve a bug in libre office which caused 100 percent cpu usage. I did something like described here
https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1584740:
I removed libreoffice-gtk*.

Problem was solved, but I now have a windows like GUI in libre office.

Windows like gui is also in BUCash, but not in ABC / btc1. I wonder why the removal of a libreoffice-gui affects BU ...

**Comment by ptschip** [comment] 2017-09-07 12:57
Confirmed...recent transactions do not show up on the  start screen however the wallet amounts are correct and you can still view your recent transactions by clicking the Transactions tab

**Comment by Justaphf** [comment] 2017-09-08 03:49
I have noticed this on Windows builds as well since around when the coin freeze UI code was merged in, currently affects the `dev` and `BitcoinCash` branches, but 'release' is OK.

**Comment by sickpig** [comment] 2017-09-11 13:49
@Justaphf thanks for noticing and reporting. It definitely seems coin freeze UI work introduce those issue.

**Comment by sickpig** [comment] 2017-09-11 15:22
@theBergmann which version of QT are you using? 
(go to "Help" -> "About Qt" menu, a dialog window with the current Qt version you are using)

**Comment by Justaphf** [comment] 2017-09-11 16:23
@sickpig I am using Qt v5.3.2, built from source natively on Windows 10 using MinGW

**Comment by theBergmann** [comment] 2017-09-11 16:47
Using v. 5.6.1

**Comment by sickpig** [comment] 2017-09-11 20:17
@Justaphf @theBergmann thanks for the info. 

On my system (ubuntu 16.04 x86_64) if I compile from source using `--with-gui=qt4` I'm not albe to see the txns list on the main screen, if I compile using  `--with-gui=qt5` the list of transactions is visible. 

On such sys I have installed via `apt` Qt 4.8.7 and Qt 5.5.1

**edit**: actually not even able to compile against Qt4, but if I rerun the configure with `--with-gui=qt4` after having used qt5 it produces a binary that hidden the list of txns.... got to dig deeper.

**edit2**: scratch everything I said before. It seems that the issue is not happening always, sometimes I see the list of recent tnx are there sometimes it is not. 
![without](https://user-images.githubusercontent.com/1469203/30296259-dfe89e0c-9743-11e7-946c-347838c817f2.png)

![with](https://user-images.githubusercontent.com/1469203/30296262-e3b47718-9743-11e7-9104-b61ce660084c.png)

**Comment by Justaphf** [comment] 2017-09-12 00:49
@sickpig Since I am compiling on Windows and need to explicitly list out the qt source directories in the configure command anyway the `--with-gui` should be redundant, but I performed a `make distclean` followed by rerunning configure with the `--with-gui=qt5` and had the same results (no recent transactions displayed).

I'll try and get Qt updated to a newer version to see if that works, but the Qt configuration options are different so I'll have to figure those out first before I can get bitcon-qt to build.

**Comment by sickpig** [comment] 2017-09-12 08:12
@Justaphf what  I meant is that I obtain variable results using the *same* binary.

**Comment by marlengit** [comment] 2017-09-30 01:17
I'll work on this now and update soon.

**Comment by marlengit** [comment] 2017-09-30 10:19
Please see fix at below link for further testing: 
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/786

**Comment by Justaphf** [comment] 2017-11-09 06:43
Now that dev has been merged to the cash branch this issue seems fixed in both branches, however the crash for mined transactions mentioned in #778 still exists.  not sure if that crash would affect this issue if a mined transaction was one of the most recent displayed on the overview tab.

**Comment by sickpig** [comment] 2018-01-11 21:44
#786 fixed the issue. closing.

**Closed as completed by sickpig** 2018-01-11 21:44 UTC
Labels: bug, GUI
