### ISSUE TITLE
Pruning not working when inside a Docker container?

### ISSUE THREAD

**Issue by mr-e-** [gandrewstone/bitcoin#362] opened 2017-03-11 16:57 UTC
I started up a brand new Digital Ocean Docker box and ran the following two scripts with "docker-compose up" but the hard drive usage just keeps on growing, it does not appear to be pruning. 

**docker-compose.yml:**

  bitcoin-data:
    image: ubuntu:latest
    volumes:
        - bitcoin:/var/lib/bitcoin/data
    
bitcoin:
    build: .
    volumes_from:
        - bitcoin-data
    ports:
        - "8333:8333"
        - "8332:8332"
        - "7777:7777"

**Dockerfile:**

  FROM debian:jessie

  ARG VERSION=1.0.1
  ARG SHA256HASH=bb604081403eefa423fb2911bf6d99258d9db655ece8c3d557f32388c06a6207

  RUN apt-get update && \
  apt-get install -y wget ca-certificates && \
    apt-get clean && \

    wget https://www.bitcoinunlimited.info/downloads/bitcoinUnlimited-${VERSION}-linux64.tar.gz && \
    echo "${SHA256HASH} bitcoinUnlimited-${VERSION}-linux64.tar.gz" | sha256sum -c - && \
    tar -xzvf bitcoinUnlimited-${VERSION}-linux64.tar.gz -C /usr/local --strip-components=1 && \
    rm bitcoinUnlimited-${VERSION}-linux64.tar.gz

  EXPOSE 8333

  ENTRYPOINT ["bitcoind", "-server", "-printtoconsole", "-datadir=/var/lib/bitcoin/data", \
            "-dbcache=256", "-whitelist=255.255.255.0", "-rpcallowip=0.0.0.0/0", \
            "-rpcuser=user", "-rpcpassword=password", "-prune=550"]
`
Not 100% sure if this is dockers fault or bitcoind but I heard there was an issue with pruning so if anyone is familiar with docker it would be great to know if I am maybe doing something wrong?

**Comment by ptschip** [comment] 2017-03-11 17:03
are blocks being connected at all?

**Comment by mr-e-** [comment] 2017-03-11 17:04
Not sure what you mean by connected but yes, it appears to be syncing just fine.

**Comment by ptschip** [comment] 2017-03-11 17:11
so you're getting blocks sync'ing, the block height is increasing but
the size on disk is getting really big?  bigger than your prune size
that you set?  is that what is happening?

and are you on the latest dev branch or are you running the current release?

i think there may be a bug in how many blocks we forward fetch when we
sync...

**Comment by mr-e-** [comment] 2017-03-11 17:14
Yes, I am on 1.0.1. Everything about the build is in the docker script above. I was told there was a previous pruning bug that would have been resolved in this release.

**Comment by sickpig** [comment] 2017-03-11 17:16
away from my PC but could somebody look if the fix for the prune issue has been applied also to the `release` branch before tagging 1.0.1?

**Comment by ftrader** [comment] 2017-03-11 18:47
I just updated my `release` checkout and looked for some of those commits and related strings, but it doesn't look like `release` has those fixes from https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/291 .

Update: checked out `1.0.1.0` tag and main.cpp:5269 doesn't have the fix from that PR :-(

**Comment by ftrader** [comment] 2017-03-21 01:19
Pruning fix was merged in version `1.0.1.1` in commit 1c38860a1714c47773ec5242317be1be2f0eef11

@mr-e- : can you test with the new release and confirm whether the issue is solved for you?

**Comment by sickpig** [comment] 2017-04-28 22:38
Closed by https://github.com/BitcoinUnlimited/BitcoinUnlimited/commit/1c38860a1714c47773ec5242317be1be2f0eef11

**Closed as completed by sickpig** 2017-04-28 22:38 UTC
