### ISSUE TITLE
Numerous test failures when netstat not installed

### ISSUE THREAD

**Issue by error10** [gandrewstone/bitcoin#584] opened 2017-05-16 15:49 UTC
Many modern Linux distributions no longer have the long-obsolete `netstat` utility installed by default. When the test suite `qa/pull-tester/rpc-tests.py` is run on such a system, numerous tests fail with the error:

> Unexpected exception caught during testing: FileNotFoundError(2, "No such file or directory: 'netstat'")

```
Test                                                Status    Time (s)
----------------------------------------------------------------------
abandonconflict.py                                  FAILED          0
bip68-112-113-p2p.py                                FAILED          0
blockchain.py                                       FAILED          0
decodescript.py                                     FAILED          0
disablewallet.py                                    FAILED          0
excessive.py                                        FAILED          0
fundrawtransaction.py                               FAILED          0
getchaintips.py                                     FAILED          0
httpbasics.py                                       FAILED          0
invalidtxrequest.py                                 FAILED          0
keypool.py                                          FAILED          0
listtransactions.py                                 FAILED          0
mempool_reorg.py                                    FAILED          0
mempool_resurrect_test.py                           FAILED          0
mempool_spendcoinbase.py                            FAILED          0
merkle_blocks.py                                    FAILED          0
multi_rpc.py                                        FAILED          0
nodehandling.py                                     FAILED          0
p2p-versionbits-warning.py                          FAILED          0
proxy_test.py                                       FAILED          0
rawtransactions.py                                  FAILED          0
receivedby.py                                       FAILED          0
reindex.py                                          FAILED          0
rest.py                                             FAILED          0
signrawtransactions.py                              FAILED          0
txn_clone.py                                        FAILED          0
txn_doublespend.py --mineblock                      FAILED          0
wallet.py                                           FAILED          0
walletbackup.py                                     FAILED          0
zapwallettxes.py                                    FAILED          0
mempool_limit.py                                    DISABLED
p2p-fullblocktest.py                                DISABLED
sendheaders.py                                      DISABLED
prioritise_transaction.py                           DISABLED
invalidblockrequest.py                              DISABLED
----------------------------------------------------------------------
                                              Total time (s):       0

0 test(s) passed / 30 test(s) failed / 30 test(s) executed
5 test(s) disabled / 0 test(s) skipped due to platform

```

In the short term it should be documented somewhere that `netstat` must be installed to run the testsuite.

In the medium to long term, the tests should be rewritten to not depend on this utility, as its future availability and/or functionality cannot be guaranteed.

**Comment by sickpig** [comment] 2017-05-17 15:19
@error10 
confirmed, removing `netstat` bin from the system will lead to a failure to all the above tests. 
Going to add a doc to state `netstat` is needed to run such tests. 

edit: this was introduced by #177, I think we should find an alternative implementation that won't depend on external system binaries or as @error10 we should document the dependency.

**Comment by sickpig** [comment] 2017-05-18 22:57
@error10 

this branch 

https://github.com/sickpig/BitcoinUnlimited/commits/port/parallel-python-tests

among other things remove the dependency on `netstat`. It is based on dev. 

I'll put up a PR shortly, I've tested locally and it works even if `netstat` is not present on the system.

**Comment by sickpig** [comment] 2017-09-12 12:03
@error10 #602 has been merged into `dev` and `BitcoinCash` branches. I verified that the issue is not reproducible anymore.

**Closed as completed by sickpig** 2017-09-12 12:03 UTC
