### ISSUE TITLE
Error reading configuration file: unrecognized option 'addressindex'

### ISSUE THREAD

**Issue by AVGoodNight** [gandrewstone/bitcoin#917] opened 2018-01-16 03:26 UTC
I have Ubuntu 16.04.3.
I installed the latest version from this
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin-unlimited/bucash
sudo apt-get update
sudo apt-get install bitcoind bitcoin-qt

Then I ran 
/usr/bin/bitcoind -conf=/mnt/volume-nyc3-03/bitcoin.conf -datadir=/mnt/volume-nyc3-03/ -testnet

and got this error
Error reading configuration file: unrecognized option 'addressindex'

If I deleted 'addressindex' and ran again I got 
Error reading configuration file: unrecognized option 'timestampindex'

My conf file
testnet=1
server=1
whitelist=127.0.0.1
addressindex=1
txindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:18332
zmqpubhashblock=tcp://127.0.0.1:18332
rpcallowip=0.0.0.0/0
rpcuser=bitcoincash
rpcpassword=local321

**Comment by sickpig** [comment] 2018-01-16 09:37
@Shmebulok,

there are no such options in BU code base, that''s way the daemon refuses to start.

Guess this is the first time you used them with BU, or you were using an older BU version that did not error out on inexistent conf options. 

The thing that is nearer is `txindex=1`, this will maintain a full transaction index, used by the `getrawtransaction` rpc call. 

Then there's an outdate pr (#395) to add an index to access the utxo by address, for more details see https://counterpartytalk.org/t/what-is-addrindex-and-why-is-it-necessary/1202

**Comment by ptschip** [comment] 2018-01-16 15:07
you have to take out the configuration entries that are not supported

Looks like you have a few that should be taken out...remove them and
then restart and you should be ok:

addressindex=1
txindex=1
timestampindex=1
spentindex=1

**Comment by ptschip** [comment] 2018-01-16 15:08
sorry, meant to say take out these three and then restart:

addressindex=1
timestampindex=1
spentindex=1

**Comment by sickpig** [comment] 2018-05-25 07:41
closing, this is the intended behavior.

**Closed as completed by sickpig** 2018-05-25 07:41 UTC
