### ISSUE TITLE
PR #593 breaks our thinblock statistics

### ISSUE THREAD

**Issue by ptschip** [gandrewstone/bitcoin#614] opened 2017-05-22 16:30 UTC
for some reason using Clear() in the stat constructor breaks all our stats gathering for thinblocks.  Our previous stats get zero'd on every block received. I suspect this is a problem for all stats and not just thinstats but i havn't verified.

https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/593

**Comment by awemany** [comment] 2017-05-24 13:07
Can reliably reproduce now. Looking into this. Very weird.

**Comment by awemany** [comment] 2017-05-26 09:18
This should have been solved by #621. At least that did it for me.

**Comment by ptschip** [comment] 2017-05-26 13:44
@awemany no, I rebuilt dev from scratch (verified 621 was in there), doesn't work for me..

**Comment by awemany** [comment] 2017-05-28 21:22
Ok, so I debugged this a bit further but am still not 100% sure yet where the problem lies. At least I am now on your page, it isn't fixed for me in HEAD either. I don't know how I got the idea that it fixed it, I must have confused something there. Can't reproduce my fix being a fix either.

Now, if you comment out the call to `Start()` in `Clear()`, it works again for me. Alternatively, setting op to
include the flag `STAT_INDIVIDUAL` works as well.

Is this a thread getting stuck?

For example it appears that the `summary` stat gets the counters reset in HEAD, but not with STAT_INDIVIDUAL.

It appears to me that STAT_INDIVIDUAL is what is meant to be used for e.g. the nBlocks variable in CThinBlockData, but I am confused regarding the exact logic that is intended here. And how value and total should interact.

I even traced writes to `thindata.nBlocks.total` and `thindata.nBlocks.value` with gdb and it appears that with the old version (before I inserted Clear()), the value is being transferred between total and value  in the timeout function.

**I also think `stat.h` needs to be urgently documented. I am willing to do that, but I think I need to pick thezerg's brain for that.**

Furthermore, is it actually safe to globally create the thindata boost timers and io service and whatnot, or should the rest of the system be initialized first?

I have a WIP series of commits to replace that with a local static variable in thinblocks.cpp instead of globals.cpp. If you guys confirm that is the right approach, I'll go ahead and make a PR for that. There's also another bug fixed, Stop() uses invalid logic right now (but isn't used anyways), I removed redundant constructors, made variables private ...


@thezerg is that what did you intend here? What should the default flags to CStatHistory be? What about the timer and global initialization?

Given that the default constructor was quite broken (left many things uninitialized before 078d163), I think it would be great if all uses of CStatHistory are rechecked to be initialized properly with sane values for that respective variable. (After updating the constructor defaults once more)

**Comment by sickpig** [comment] 2017-05-30 21:51
@awemany any update on this issue?

(ps thezerg handle on GH is @gandrewstone)

**Comment by sickpig** [comment] 2017-06-08 06:52
@ptschip @awemany any updates on this one ?

**Comment by ptschip** [comment] 2017-07-26 18:53
@awemany any updates on this...we really do need to get to the bottom of this since we're releasing the dev branch at least as BUCash right now.

**Comment by sickpig** [comment] 2017-08-14 10:41
@ptschip @awemany any updates?

**Comment by ptschip** [comment] 2017-10-13 14:28
fixed in #792

**Comment by sickpig** [comment] 2018-05-02 15:18
closing due to #792

**Closed as completed by sickpig** 2018-05-02 15:18 UTC
