### ISSUE TITLE
Assertion failed at startup, trying to import blockchain files from Core 0.14

### ISSUE THREAD

**Issue by pinheadmz** [gandrewstone/bitcoin#399] opened 2017-03-24 16:22 UTC
Experimenting with bitcoinUnlimited-1.0.0 (so maybe I'm just out of date) in `-regtest` mode. Copied regtest data directory generated by Core 0.14 and attempted to start BU with `-datadir=...` to simulate switching clients without re-syncing entire chain:

```
2017-03-24 15:58:47 Bitcoin version v1.0.0.1-b471620 (2017-01-30 21:13:35 -0500)
2017-03-24 15:58:47 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2017-03-24 15:58:47 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2017-03-24 15:58:47 Default data directory /Users/studio1/Library/Application Support/Bitcoin
2017-03-24 15:58:47 Using data directory /Volumes/untitled/bitcoin_tools/ddircopy/regtest
2017-03-24 15:58:47 Using config file /Volumes/untitled/bitcoin_tools/ddircopy/bitcoin.conf
2017-03-24 15:58:47 Using at most 125 connections (275 file descriptors available)
2017-03-24 15:58:47 Using 12 threads for script verification
2017-03-24 15:58:47 scheduler thread start
2017-03-24 15:58:47 HTTP: creating work queue of depth 16
2017-03-24 15:58:47 No rpcpassword set - using random cookie authentication
2017-03-24 15:58:47 Generated RPC authentication cookie /Volumes/untitled/bitcoin_tools/ddircopy/regtest/.cookie
2017-03-24 15:58:47 HTTP: starting 4 worker threads
2017-03-24 15:58:47 Using wallet wallet.dat
2017-03-24 15:58:47 init message: Verifying wallet...
2017-03-24 15:58:47 CDBEnv::Open: LogDir=/Volumes/untitled/bitcoin_tools/ddircopy/regtest/database ErrorFile=/Volumes/untitled/bitcoin_tools/ddircopy/regtest/db.log
2017-03-24 15:58:47 Bound to [::]:18444
2017-03-24 15:58:47 Bound to 0.0.0.0:18444
2017-03-24 15:58:47 Cache configuration:
2017-03-24 15:58:47 * Using 2.0MiB for block index database
2017-03-24 15:58:47 * Using 82.5MiB for chain state database
2017-03-24 15:58:47 * Using 215.5MiB for in-memory UTXO set
2017-03-24 15:58:47 init message: Loading block index...
2017-03-24 15:58:47 Opening LevelDB in /Volumes/untitled/bitcoin_tools/ddircopy/regtest/blocks/index
2017-03-24 15:58:47 Opened LevelDB successfully
2017-03-24 15:58:47 Using obfuscation key for /Volumes/untitled/bitcoin_tools/ddircopy/regtest/blocks/index: 0000000000000000
2017-03-24 15:58:47 Opening LevelDB in /Volumes/untitled/bitcoin_tools/ddircopy/regtest/chainstate
2017-03-24 15:58:47 Opened LevelDB successfully
2017-03-24 15:58:47 Using obfuscation key for /Volumes/untitled/bitcoin_tools/ddircopy/regtest/chainstate: 0115a56804cd2974
2017-03-24 15:58:47 LoadBlockIndexDB: last block file = 0
2017-03-24 15:58:47 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=504, size=2579941, heights=0...503, time=2011-02-02...2017-03-21)
2017-03-24 15:58:47 Checking all blk files are present...
2017-03-24 15:58:47 LoadBlockIndexDB: transaction index disabled
Assertion failed: (!setBlockIndexCandidates.empty()), function PruneBlockIndexCandidates, file main.cpp, line 3124.
```

**Comment by ptschip** [comment] 2017-03-24 16:48
rather than copy the files over can you just try launcing BU using the
same datadir as the Core 14 client.  Just to rule out that anything go
missed in the copy over.

also when you were running on Core 14 were you doing any segwit type
tests or creating and segwit type blocks?

**Comment by pinheadmz** [comment] 2017-03-24 17:10
I wasn't yet at this point in my test. But SegWit was "activated" on the regtest chain (in regtest SegWit is fully active after `144*3=432` blocks, and my regtest chain is 500 high). Switching back to Core and `getblock` height 440 I get this back:

```
  "strippedsize": 228,
  "size": 264,
  (...)
  "tx": [
    "ab440ebc0349b227bed35564bdc162073136c5f2d6136f25e5b9e56e2b86dc25"
  ],
```

So I guess in Core even though there are no SegWit transactions in a block, there is still some `264-228=36` bytes that BU wouldn't expect? Can you help me understand what this function is doing?

https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/src/main.cpp#L3126

**Comment by pinheadmz** [comment] 2017-03-24 17:16
Hm actually BIP141 spec suggests that the coinbase transaction has a `wtxid`, so technically there *is* a SegWit tx in this block.

**Comment by pinheadmz** [comment] 2017-03-24 17:20
I guess the real way to do this would be to set up Core and BU as two peers and transfer the backwards-compatible blocks over to BU the way peers would sync on mainnet.

**Comment by ptschip** [comment] 2017-03-24 17:22
so basically the problem looks like it's caused by an incompatible
blockchain.

**Comment by ptschip** [comment] 2017-03-24 17:32
that would be a good test...i think thought at some point when you get
an incomaptible block the sync may stop but it would be good to see what
happens!

**Comment by ftrader** [comment] 2017-03-24 20:08
@pinheadmz : good test, and you seem to have caught a fish!

It would be interesting to clarify exactly why a SegWit tx in the chain. Did you run some Core regtest(s) which generated the datadir that you copied to use for BU tests? That might explain a SegWit tx in it.

P.S. I thought Core had removed the internal miner. I'm not up to speed on Core 0.14 - how does it mine on regtestnet? Maybe there are clues in that re: how it mines after block 432 / whenever SegWit activates during the regtest.

**Comment by pinheadmz** [comment] 2017-03-24 22:15
I re-tried this test with only 100 blocks so SegWit doesn't activate, and BU successfully picked up on the Core blockchain files. Generating another 300 blocks with Core created a data directory that BU crashed on. I wouldn't expect BU to be able to run on SegWit blocks, but it returned an assertion error instead of corrupt database error or something like that. It also seems that after SegWit is activated in Core, coinbase transactions are formatted according to BIP143, described at https://github.com/bitcoin/bitcoin/blob/v0.13.1rc2/src/primitives/transaction.h#L275

**Comment by sickpig** [comment] 2017-04-28 23:01
Closing for now. Problem is due to BU not implementing SegWit.

**Closed as completed by sickpig** 2017-04-28 23:01 UTC
