### ISSUE TITLE
minlimitertxfee is not honoured

### ISSUE THREAD

**Issue by buuser** [gandrewstone/bitcoin#125] opened 2016-10-22 14:12 UTC
Please see the following line of code:

https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/0.12.1bu/src/main.cpp#L1381

```
 if (fLimitFree && nFees < ::minRelayTxFee.GetFee(nSize) && !fSpendsCoinbase && dPriority < 150000000)
```

As a result of this line it appears that some transactions with an extremely low sat/byte fee ratio are allowed into the mempool, even when a high value is given for minlimitertxfee. 

This check dPriority < 150000000 appears to be allowing these transactions through as they don't enter this if statement and so aren't being rejected. Is there a reason for this change?

For example the following transactions were allowed into my mempool, which had a minlimitertxfee value of 55 sat/byte. 

```
sat/byte 1 d02285a4c829885473cf112bd670730a41982e2662b7c9770f2951e48531a95b size:14798 pri 167089113
sat/byte 1 6c187543414df0d4788b8e8351a7a2d39b9e99b88085e88b0d730b9a1ab54fa3 size:14800 pri 153205977
sat/byte 1 c6366984dbdeadab84b7add71e078015ce5ae90cd7cf8c06336a727eec99e949 size:14797 pri 167087363
sat/byte 1 e1c6a3ef131f23c1967752f46597bf1c6ac74845c94def75ad80bb59b307ebf4 size:14802 pri 167027613
```

Despite their ratio being 1 sat/byte, they were allowed to enter the mempool as their priorities had been calculated to be higher than 150000000. I think the user should be allowed to override this behaviour.

**Comment by ptschip** [comment] 2016-10-25 18:14
are you able to submit a PR for this?  otherwise I'll put it on my TODO
list.

thanks again!

**Comment by ptschip** [comment] 2016-10-25 18:48
Thanks for reporting it and doing the analysis.  To be clear,
minlimitertxfeeor minrelaytxfee, for that matter, do not necessarily
prevent tx's from propagating, they only indicate whether a tx _may_ be
subject to rate limiting depending on how many low fee tx's were sent in
the last 10 minutes.  But I do agree with you that this setting should
be configurable.  BU is all about market forces and choice so I believe
this enhancement request would be in alignment BU's philosophy.

**Comment by buuser** [comment] 2016-10-25 19:00
@ptschip thanks for responding, much appreciated. I had switched from classic to BU and this was one thing I noticed, which meant my mempool grew significantly larger than it did when running classic. I guess I was just asking if there was a reason for this change. 

I'm not sure though what the best solution to this would be. I have been running with a customized version of BU with the line of code above amended, which seems to revert the mempool to how classic behaves.

However I still do see some (not many) transactions in my mempool with zero fee, I haven't had a chance to look through the code to see how these are getting through, even though I have my limitfreerelay parameter set to 0. 

Just to be clear, I absolutely support the notion that some transactions should be free. I'm simply trying to understand how the client behaves when certain parameters are configured. 

Thinking off the top of my head I'm not sure how you would allow the user to control the logic in the line above, I need to have think about it :-) I guess you could just make the 150000000 parameter configurable.

**Comment by ptschip** [comment] 2016-10-25 19:53
you know what, i think i'm going to prepare a PR to have this take out. 
I'm going to do a little testing to make sure it doesn't break anything
but I think this parameter has outlived it's usefulness.

**Comment by ptschip** [comment] 2016-10-25 21:55
thanks for reporting this BTW.

I have it up and running and it's working much better.  As it was
intended to and with less user confusion over the maxlimitertxfee...

thanks again!

**Comment by ptschip** [comment] 2016-10-25 21:56
the thinking was to allow and propagate more free an high priorty tx's
and also always allow coinbase spends ...a high priority tx is considere
to be around 60,000,000 (if my memory serves), plus or minus, so the
150,000,000 we allow is pretty high up there. But the problem has been
with these large txs floating around in some cases for almost a year
now, that never get mined,  their priority has risen over time and as a
result they're getting into the mempools and then forwarded on -  I
think that's what's happening.  I'm wondering if we should revist that
here and take that out of our code completely. 

But  I think under normal circumstances though, let's say normal being
we have larger blocks an the mempools are getting recycled end emptied
regularly , then allowing more high priority txs would be fine but in
these strange days of 1MB blocks these txs are remaining forever cycling
through network while increasing in priority over time and eventually
getting into the mempools.

**Comment by buuser** [comment] 2016-10-26 09:11
Yep this is exactly what I was seeing, transactions from a long time ago, which were fairly large in size were slowly entering the mempool and causing it to grow. The actual number of transactions in the mempool was around the same. 

It's interesting that there is a node/client out there which must be rebroadcasting them as I believe the default is for transactions to age out of the mempool after 72 hours.

Thanks for taking a look at this, much appreciated!

**Comment by sickpig** [comment] 2016-11-08 09:21
@buuser PR #134 has been merged, does this fox the issue for you? If this is the case you could close the issue. thanks

**Comment by discoltk** [comment] 2017-01-02 14:18
Shit.   You guys removed minrelaytxfee ?       I partially depended on that for .. reasons.   
I guess I was stupid to assume all the existing configurables worked.

EDIT:   As a matter of constructive feedback, can you make it so that the daemon will not start if there are non-supported configurables set in the config file?

**Comment by ptschip** [comment] 2017-01-02 14:28
minrelaytxfee is still in use but the value is dynamic ...it rises and
falls depending on mempool size, somewhat similar to what core does but
we we invoke mempool limiting earlier.  However, it  is configurable so
you can allow whatever transactions you wan't or don't want.

**Comment by ptschip** [comment] 2017-01-02 14:31
btw, this bug report was for minlimitertxfee, not minrelaytxfee...

**Comment by discoltk** [comment] 2017-01-02 14:32
I was using it as a prophylactic on my service which is at high risk of being double spent.   Because I was protected there I didn't know a bug I'd written exposed me (because I was never seeing the low fee tx's).  So switching to UL made it possible for me to see TX's I'd never have seen unless they confirmed.   Fortunately I had more checks and caught it quickly.    

But what you're saying is the behavior of that config option is significantly altered.   As in, unconfirmed tx with fees less than minrelaytxfee may be relayed?

**Comment by ptschip** [comment] 2017-01-02 14:37
@discoltk  that has always been the behavior of bitcoin.  It has always been possible to send tx's with values less than the minrelaytxfee...minrelaytxfee only tells the node what is considered a free transaction, however, once it is flagged as a free transaction it comes under the effect of -limitfreerelay...the default for limitfreerelay is 150KB per 10 min period, which means every 10 mins  there are 150KB of free transactions that can be forwarded.  This is nothing new and has been in place for at least as long as I can remember.

**Comment by ptschip** [comment] 2017-01-02 14:38
@discoltk I'm unclear as to what youi are trying to do?  do you want to see ALL tx's or are you trying to filter them out from getting in the mempool?

**Comment by discoltk** [comment] 2017-01-02 14:42
I want to do what core does, which is to NOT relay any transaction with a fee less than minrelaytxfee.

**Comment by discoltk** [comment] 2017-01-02 14:47
If your description is correct, perhaps it was never working completely before.   I'm seeing lots of misinformation if that is right.  

Do I need to set limitfreerelay to 0 to achieve what I'm looking for?

**Comment by ptschip** [comment] 2017-01-02 14:53
the set your "minlimitertxfee=<satoshi/byte>"    where satoshi/byte can be a floating point number...so if you want a  minrelaytxfee of 1000 then set your "minlimitertxfee=1.0".   The minlimitertxfee is essentially the starting value for "minrelaytxfee"/1000.

If you want identical action to core then you should also set your maxlimitertxfee=1.0 as well...then you won't be doing any further limiting until you hit the maxmempool size which is where Core will invoke their own mempool limiter.

So these two settings should work for you:
minlimitertxfee=1.0
maxlimitertxfee=1.0

**Comment by ptschip** [comment] 2017-01-02 14:54
@discoltk  Yes, if you really want to stop all tx's below a certain value then you also need to set limitfreerelay=0

EDIT: whether you're using Core or BU

**Comment by discoltk** [comment] 2017-01-02 14:55
@ptschip Awesome, thanks much!    Its late here and wasn't in the right mood to deal with this, but looks like mostly brought about by my own false assumptions.   =)

**Comment by ptschip** [comment] 2017-01-02 14:55
@discoltk no problem...glad to have helped.

**Comment by discoltk** [comment] 2017-01-02 16:03
@ptschip Unfortunately, that didn't work.   Still relaying small fee tx's..

**Comment by ptschip** [comment] 2017-01-02 16:10
there was a bug that was fixed , which is the reason for this bug report
but it won't be out until our latest release which should be within a
week or so.  But if you can compile your own bitcoind,  I can show you
which line to edit.

**Comment by ftrader** [comment] 2017-01-02 16:22
Does https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/197 relate to this as well?

**Comment by ptschip** [comment] 2017-01-02 16:26
yes...that's something new that I only thought about because of what we
were discussing today, but there was also something else that was fixed
a few weeks back relating to priority...both are on the same line of
code though.

**Comment by gandrewstone** [comment] 2017-01-13 22:38
closing, fixed...

**Closed as completed by gandrewstone** 2017-01-13 22:38 UTC
